spring.datasource.url=jdbc:mysql://edurefuerzo-danieltest02027-f0b9.j.aivencloud.com:13980/defaultdb?ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_3O_XCz2nIdkx7SwYR49
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true